---
title: "Nominal house prices data in Luxembourg"
author: "Bruno Rodrigues"
date: today
---

```{r development, include=FALSE}
library(dplyr)
library(ggplot2)
library(janitor)
library(purrr)
library(readxl)
library(rvest)
library(stringr)
library(testthat)
```

Let’s plot some data for good measure:

```{r function-get_plot}
#' Draw some plots
#'
#' @param data_to_plot Data set to plot
#' @return A ggplot
#' @export
get_plot <- function(data_to_plot){
  ggplot(data_to_plot) +
    geom_line(aes(y = average_price_m2_nominal_euros,
                  x = year,
                  group = locality,
                  colour = locality))
}

```

```{r}
data(commune_level_data, package = "luHousePrices")
data(country_level_data, package = "luHousePrices")
```

```{r}
commune_level_data %>%
  dplyr::filter(locality %in% c("Luxembourg",
                                "Esch-sur-Alzette",
                                "Diekirch")) %>%
  get_plot()

country_level_data %>%
  get_plot()
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "minimal/my_article.qmd", vignette_name = "Data cleaning", overwrite = T)
```
