# WARNING - Generated by {fusen} from /minimal/my_article.qmd: do not edit by hand

#' Draw some plots
#'
#' @param data_to_plot Data set to plot
#' @return A ggplot
#' @export
get_plot <- function(data_to_plot){
  ggplot(data_to_plot) +
    geom_line(aes(y = average_price_m2_nominal_euros,
                  x = year,
                  group = locality,
                  colour = locality))
}

