# WARNING - Generated by {fusen} from /minimal/save_data.qmd: do not edit by hand

#' get_raw_data Gets raw nominal house price data from LU Open Data Portal
#'
#' @param url Optional: Persistent url to the data
#' @return A data frame
#' @export
get_raw_data <- function(url = "https://data.public.lu/fr/datasets/r/1d20f982-57e1-4ae2-a278-dc78c88c21dc"){
  raw_data <- tempfile(fileext = ".xlsx")

  download.file(url, raw_data)

  #raw_data <- "c:/Users/LLP685/Downloads/vente-appartement-2010-2021.xlsx"
  sheets <- excel_sheets(raw_data)

  read_clean <- function(..., sheet){
    read_excel(..., sheet = sheet) %>%
      mutate(year = sheet)
  }

  raw_data <- map_dfr(sheets,
                      ~read_clean(raw_data,
                                  skip = 10,
                                  sheet = .)) %>%
    clean_names()

  raw_data %>%
    rename(locality = commune,
           n_offers = nombre_doffres,
           average_price_nominal_euros = prix_moyen_annonce_en_courant,
           average_price_m2_nominal_euros = prix_moyen_annonce_au_m2_en_courant,
           average_price_m2_nominal_euros = prix_moyen_annonce_au_m2_en_courant
           ) %>%
    mutate(locality = str_trim(locality)) %>%
    select(year, locality, n_offers, starts_with("average"))

}

