# WARNING - Generated by {fusen} from /minimal/save_data.qmd: do not edit by hand

#' get_current_communes Downloads list of current communes from Wikipedia
#'
#' @param url Optional: Persistent url to the data
#' @param table_position Optional: Scraping returns a list of tables, so users need to specify the correct table. Defaults to 1, the position of the table as of writing.
#' @return A data frame
#' @export

get_current_communes <- function(url = "https://en.wikipedia.org/wiki/List_of_communes_of_Luxembourg",
                                 table_position = 1){
  read_html(url) %>%
    html_table() %>%
    pluck(table_position) %>%
    clean_names()
}

